### ISSUE TITLE
Save memberreg in sender scope

### ISSUE THREAD

**Issue by nanonano7** [eosdac/eosdactoken#11]
afaik the agreedterms of the members are stored in a single table on the contract scope.
If i want to get the agreedterms of a single member i have to query the whole table with the contract scope which could be quite wasteful with a lot of members.
Would it make sense to also save the agreedterms in the senders scope with just a single row?
That way i wouldnt have to query the whole table

**Comment by dallasjohnson** [comment]
Yes, `Agreedterms` are stored in the one table and scoped to the contract. This makes is easy for iterating through all registered members from within contract code. If it was scoped to each member then we could only request for one member at a time. Based on our current use cases we do not need to iterate through members so changing it to member scoped wouldn't be a problem now. However I believe the same result can be achieved by fetching from the table and setting a lower and upper bounds for only the accountID we want. This should then return only the single row rather than the whole table. This has the downside of making the request to the table more complicated (with the extra lower/upper params) but keeps the ability to iterate through all members in contract code if we need it in the future. I've discussed this with Nano and we need to check if my understanding of lower/upper bounds is correct. If it doesn't work then it makes complete sense to change the scope to member specific.

**Comment by nanonano7** [comment]
lower_bound: account_name, limit:1
works too
